server:
  port: 3333
spring:
  application:
    name: seckill-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lovecloud?characterEncoding=utf-8
    username: root
    password: 123456
  rabbitmq:
    host: 121.199.13.65
    username: van
    password: 123456

eureka:
  client:
    service‐url:
      defaultZone: http://localhost:8888/eureka

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  hystrix:
    enabled: true

ribbon:
  eureka:
    enabled: true