eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8080
spring:
  application:
    name: zuul
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  routes:
    order:
      path: /order/**
      serviceId: seckill-order
    goods:
      path: /goods/**
      serviceId: seckill-goods
    user:
      path: /user/**
      serviceId: seckill-user
    stock:
      path: /stock/**
      serviceId: seckill-stock